### ISSUE TITLE
659の作り直し

### ISSUE THREAD

**Issue by book000** [jaoafa/jaotan-659#4]

**Comment by book000** [comment]
ちょっと方針転換。ランキングに記録されるもの以外はデータベースへの登録を**行わない**。
具体的には、

- 2回目以降のトライ
- 有効時間外の対象メッセージ
- 非/未対象メッセージ

はランキング/DBに記録しない。したがって、これらに対して行われる投稿時刻返信メッセージは30秒後に自動削除される

**Comment by kohonayoshi** [comment]
5分後でいいかと。30秒後だとVCSpeakerの👀みたいに頻繁に投稿と削除が連続してやべうまくコピーできないうわ＞700＜みたいになる可能性があり得る

**Comment by book000** [comment]
> 5分後

fixed: https://github.com/jaoafa/jaotan-659/commit/8e50cecc3cfb20ba80c278785e4b518946b18880

**Comment by book000** [comment]
近日中本リリースを行うこと。
